export const BASE_URL = {
  // 共通画面もしくは共通で使用
  /** ダッシュボード取得API */ DASHBOARD: `${app.env.API_URL}dashboard/v1`,
  /** お客様情報(アカウント取得)API*/ USER_INFO: `${app.env.API_URL}account/v1`,
  /** ログインユーザー認可情報取得API*/ USER_AUTHORIZATION: `${app.env.API_URL}account/authorization/v1`,
  /** 買い手向け発注済み発注業務概況一覧検索API*/ OVERVIEW_BUYER: `${app.env.API_URL}overviews/buyer/v6`,
  /** 売り手向け受注済み発注業務概況一覧検索API*/ OVERVIEW_SELLER: `${app.env.API_URL}overviews/seller/v6`,
  /** 買い手向け発注書一覧検索API*/ DOCUMENT_ORDER_BUYER: `${app.env.API_URL}order-document/buyer/v4`,
  /** 売り手向け発注書一覧検索API*/ DOCUMENT_ORDER_SELLER: `${app.env.API_URL}order-document/seller/v3`,
  /** 買い手向け発注請書一覧検索API*/ DOCUMENT_CONFIRMATION_BUYER: `${app.env.API_URL}order-confirmation-document/buyer/v1`,
  /** 売り手向け発注請書一覧検索API*/ DOCUMENT_CONFIRMATION_SELLER: `${app.env.API_URL}order-confirmation-document/seller/v1`,
  /** 買い手向け納品書一覧検索API*/ DOCUMENT_DELIVERY_BUYER: `${app.env.API_URL}delivery-document/buyer/v3`,
  /** 売り手向け納品書一覧検索API*/ DOCUMENT_DELIVERY_SELLER: `${app.env.API_URL}delivery-document/seller/v3`,
  /** 買い手向け検収書一覧検索API*/ DOCUMENT_ACCEPTANCE_BUYER: `${app.env.API_URL}acceptance-document/buyer/v3`,
  /** 売り手向け検収書一覧検索API*/ DOCUMENT_ACCEPTANCE_SELLER: `${app.env.API_URL}acceptance-document/seller/v3`,
  /** 買い手向け下書き発注業務概況一覧検索API*/ OVERVIEW_BUYER_DRAFT: `${app.env.API_URL}overviews/buyer/draft/v3`,
  /** 買い手向け未対応通知一覧検索API*/ UN_HANDLING_NOTIFICATION_BUYER: `${app.env.API_URL}unhandling-notification/buyer/v2`,
  /** 売り手向け未対応通知一覧検索API*/ UN_HANDLING_NOTIFICATION_SELLER: `${app.env.API_URL}unhandling-notification/seller/v2`,
  /** 買い手向け未確認通知一覧検索API*/ UN_CONFIRMING_NOTIFICATION_BUYER: `${app.env.API_URL}unconfirming-notification/buyer/v2`,
  /** 売り手向け未確認通知一覧検索API*/ UN_CONFIRMING_NOTIFICATION_SELLER: `${app.env.API_URL}unconfirming-notification/seller/v2`,
  /** 買い手向け工事案件一覧API*/ VOLUME_CONSTRUCTION_BUYER: `${app.env.API_URL}constructions/buyer/v2`,
  /** 売り手向け工事案件一覧API*/ VOLUME_CONSTRUCTION_SELLER: `${app.env.API_URL}constructions/seller/v2`,
  /** 買い手出来高報告書一覧検索API */ VOLUME_REPORT_DOCUMENT_BUYER: `${app.env.API_URL}volume-report-document/buyer/v1`,
  /** 売り手出来高報告書一覧検索API */ VOLUME_REPORT_DOCUMENT_SELLER: `${app.env.API_URL}volume-report-document/seller/v1`,
  /** 買い手向け発注済み業務概況一覧出力API */ OVERVIEW_BUYER_CSV: `${app.env.API_URL}overviews/buyer/v1/csv`,
  /** 売り手向け受注済み発注業務概況一覧出力API */ OVERVIEW_SELLER_CSV: `${app.env.API_URL}overviews/seller/v1/csv`,
  /** 買い手向け発注書一覧csv出力API*/ DOCUMENT_ORDER_BUYER_CSV: `${app.env.API_URL}order-document/buyer/v2/csv`,
  /** 売り手向け発注書一覧csv出力API*/ DOCUMENT_ORDER_SELLER_CSV: `${app.env.API_URL}order-document/seller/v2/csv`,
  /** 買い手向け発注請書一覧csv出力API*/ DOCUMENT_CONFIRMATION_BUYER_CSV: `${app.env.API_URL}order-confirmation-document/buyer/v1/csv`,
  /** 売り手向け発注請書一覧csv出力API*/ DOCUMENT_CONFIRMATION_SELLER_CSV: `${app.env.API_URL}order-confirmation-document/seller/v1/csv`,
  /** 買い手向け納品書一覧csv出力API*/ DOCUMENT_DELIVERY_BUYER_CSV: `${app.env.API_URL}delivery-document/buyer/v2/csv`,
  /** 売り手向け納品書一覧csv出力API*/ DOCUMENT_DELIVERY_SELLER_CSV: `${app.env.API_URL}delivery-document/seller/v2/csv`,
  /** 買い手向け検収書一覧csv出力API*/ DOCUMENT_ACCEPTANCE_BUYER_CSV: `${app.env.API_URL}acceptance-document/buyer/v2/csv`,
  /** 売り手向け検収書一覧csv出力API*/ DOCUMENT_ACCEPTANCE_SELLER_CSV: `${app.env.API_URL}acceptance-document/seller/v2/csv`,
  /** 買い手向け出来高報告書一覧csv出力API*/ DOCUMENT_VOLUME_REPORT_BUYER_CSV: `${app.env.API_URL}volume-report-document/buyer/v1/csv`,
  /** 売り手向け出来高報告書一覧csv出力API*/ DOCUMENT_VOLUME_REPORT_SELLER_CSV: `${app.env.API_URL}volume-report-document/seller/v1/csv`,
  /** 発注業務文書一覧API */ ORDER_BUSINESS_DOCUMENTS: `${app.env.API_URL}order-business-documents/v1`,
  /** 業務文書一覧API */ BUSINESS_DOCUMENTS: `${app.env.API_URL}business-documents/v2`,
  /** ユーザーアカウント一覧検索API */ USER_ACCOUNTS_SEARCH: `${app.env.API_URL}employees/search/v1`,
  /** 組織アカウント一覧検索API */ SECTOR_ACCOUNTS_SEARCH: `${app.env.API_URL}departments/search/v1`,
  /** 取引先API */ TRADE_CLIENTS: `${app.env.API_URL}customer/v1`,
  /** 仮取引先API */ PRE_CUSTOMER: `${app.env.API_URL}pre-customer/v1`,
  /** 仮取引先検索API */ PRE_CUSTOMER_SEARCH: `${app.env.API_URL}pre-customer/search/v1`,
  /** 修正中仮取引先画面_初期表示データ取得API */ IN_REVISION_PRE_CUSTOMER: `${app.env.API_URL}pre-customer/in-revision/v1`,
  /** 仮取引先更新API */ PRE_CUSTOMER_MODIFY: `${app.env.API_URL}pre-customer/modify/v1`,
  /** 仕掛中招待状画面_初期表示データ取得API */ IN_PROCESS_INVITATION: `${app.env.API_URL}in-process-invitation/v1`,
  /** 取引先招待API */ CUSTOMER_INVITE: `${app.env.API_URL}customer/invite/v1`,
  /** 未承認取引先一覧取得API */ CUSTOMER_UNAPPROVED: `${app.env.API_URL}customer/unapproved/v1`,
  /** 招待済取引先承認API */ CUSTOMER_APPROVE: `${app.env.API_URL}customer/approve/v1`,
  /** 招待済取引先否認API */ CUSTOMER_REJECT: `${app.env.API_URL}customer/reject/v1`,
  /** 買い手取引先一覧検索API */ BUYER_SEARCH: `${app.env.API_URL}customer/search/buyer/v1`,
  /** 売り手取引先一覧検索API */ SELLER_SEARCH: `${app.env.API_URL}customer/search/seller/v1`,
  /** 買い手取引先選択API */ BUYER_SELECT: `${app.env.API_URL}customer/select/buyer/v1`,
  /** 売り手取引先選択API */ SELLER_SELECT: `${app.env.API_URL}customer/select/seller/v2`,
  /** 買い手取引先修正API */ BUYER_MODIFY: `${app.env.API_URL}customer/modify/buyer/v1`,
  /** 売り手取引先修正API */ SELLER_MODIFY: `${app.env.API_URL}customer/modify/seller/v2`,
  /** 売り手取引先表示/非表示切り替えAPI */ SELLER_DISPLAY: `${app.env.API_URL}customer/display/seller/v1`,
  /** 受注企業（売り手）宛先追加API */ SHARE_COMPANY_DESTINATION: `${app.env.API_URL}share-company-destination/v1`,
  /** 受注企業（売り手）宛先修正API */ SHARE_COMPANY_DESTINATION_MODIFY: `${app.env.API_URL}share-company-destination/modify/v1`,
  /** 請求先(発行先コード)更新API*/ BILLING_ADDRESS_CONNECT: `${app.env.API_URL}billing-address/connect/v1`,
  /** 発注概況API */ OVERVIEW: `${app.env.API_URL}overviews/v6`,
  /** ファイルアップロード（添付ファイル仮登録）API */ FILE_UPLOADS: `${app.env.API_URL}attachment-files/upload/v1`,
  // ATTACHMENT_FILE_ADDとATTACHMENT_FILEはバージョンの違いのみでパスは同一
  /** 添付ファイル登録API */ ATTACHMENT_FILE_ADD: `${app.env.API_URL}attachment-files/v1`,
  /** 添付ファイル取得API */ ATTACHMENT_FILE: `${app.env.API_URL}attachment-files/v2`,
  /** 添付ファイルダウンロードAPI */ ATTACHMENT_FILE_DOWNLOAD: `${app.env.API_URL}attachment-files/download/v1`,
  /** 約款ファイルダウンロードAPI(業務ルール紐付) */ CLAUSE_FILE_DOWNLOAD: `${app.env.API_URL}clause-files/download/v1`,
  /** 約款ファイルダウンロードAPI(ドキュメント紐付) */ ORDER_CLAUSE_FILE_DOWNLOAD: `${app.env.API_URL}order-clause-files/download/v1`,
  /** 添付ファイル削除 API */ ATTACHMENT_FILE_REMOVE: `${app.env.API_URL}attachment-files/delete/v1`,
  /** 履歴情報を取得するAPI */ ATTACHMENT_FILE_HISTORY: `${app.env.API_URL}attachment-files/v2/historyFile`,
  // OWN_COMPANY_MANAGEMENT_SAVEとOWN_COMPANY_MANAGEMENTはバージョンの違いのみでパスは同一
  /** 自社管理項目保存API */ OWN_COMPANY_MANAGEMENT_SAVE: `${app.env.API_URL}individual-trade/private-fields/v1`,
  /** 自社管理項目選択API */ OWN_COMPANY_MANAGEMENT: `${app.env.API_URL}individual-trade/private-fields/v2`,
  /** メッセージ送信API */ MESSAGE: `${app.env.API_URL}message/v1`,
  /** タイムライン取得API */ TIME_LINE: `${app.env.API_URL}time-line/v2`,
  /** 取消依頼書提出API*/ CANCELLATION_DOCUMENT: `${app.env.API_URL}cancellation-document/v1`,
  /** 取消依頼書取り下げAPI*/ CANCELLATION_DOCUMENT_REVERT: `${app.env.API_URL}cancellation-document/revert/v1`,
  /** 取消依頼書承認API*/ CANCELLATION_DOCUMENT_APPROVE: `${app.env.API_URL}cancellation-document/approve/v1`,
  /** 個別取引終了API*/ INDIVIDUAL_TRADE: `${app.env.API_URL}individual-trade/v1`,
  /** 見積依頼書_遷移データ取得API */ GET_ESTIMATE_REQUEST: `${app.env.API_URL}estimate-request-document/v1`,
  /** 見積書_遷移データ取得API */ GET_ESTIMATE: `${app.env.API_URL}estimate-document/v1`,
  /** 請求金額計算API */ INVOICE_STATEMENT_CALCULATE: `${app.env.API_URL}billing-amount/calculate/v1`,
  /** 契約書候補一覧検索API */ CONTRACT_CANDIDATE: `${app.env.API_URL}contract-candidate/v1`,
  /** 当事者電子署名契約書画面_初期表示データ取得API */ PARTY_DIGITAL_SIGN_CONTRACT_PAGE: `${app.env.API_URL}party-digital-sign-contract-document-page/v1`,
  /** 当事者電子署名契約書付加API */ PARTY_DIGITAL_SIGN_CONTRACT: `${app.env.API_URL}party-digital-sign-contract/v1`,
  /** 当事者電子署名契約書除去API */ PARTY_DIGITAL_SIGN_CONTRACT_DETACH: `${app.env.API_URL}party-digital-sign-contract/detach/v1`,
  /** 第三者電子署名契約書画面_初期表示データ取得API */ THIRD_PARTY_DIGITAL_SIGN_CONTRACT_PAGE: `${app.env.API_URL}third-party-digital-sign-contract-document-page/v1`,
  /** 第三者電子署名契約書付加API */ THIRD_PARTY_DIGITAL_SIGN_CONTRACT: `${app.env.API_URL}third-party-digital-sign-contract/v1`,
  /** 第三者電子署名契約書除去API */ THIRD_PARTY_DIGITAL_SIGN_CONTRACT_DETACH: `${app.env.API_URL}third-party-digital-sign-contract/detach/v1`,
  /** 副本契約書画面_初期表示データ取得API */ DUPLICATE_CONTRACT_PAGE: `${app.env.API_URL}duplicate-contract-document-page/v1`,
  /** 副本契約書付加API */ DUPLICATE_CONTRACT: `${app.env.API_URL}duplicate-contract/v1`,
  /** 副本契約書除去API */ DUPLICATE_CONTRACT_DETACH: `${app.env.API_URL}duplicate-contract/detach/v1`,
  /** 複数サービス同時招待管理TBL取得API */ ES_MULTI_INVITATION_GET: `${app.env.API_URL}multiinvite/v1`,

  // 都度見積で使用
  // BUSINESS_RULE_CREATEとBUSINESS_RULEはバージョンの違いのみでパスは同一
  /** 業務ルール_テンプレート新規作成 */ BUSINESS_RULE_CREATE: `${app.env.API_URL}business-rule/v4`,
  /** 業務ルール_テンプレート一覧 */ BUSINESS_RULE: `${app.env.API_URL}business-rule/v2`,
  /** 業務ルール_テンプレート表示/非表示切替 */ BUSINESS_RULE_DISPLAY: `${app.env.API_URL}business-rule/v1`,
  /** 業務ルール_業務規定取得API */ BUSINESS_RULE_PROVISION: `${app.env.API_URL}business-provision/v1`,
  /** 業務ルール_文書規定パック取得API（編集でも使用（文書規定パック変更API）） */ BUSINESS_RULE_DOCUMENT: `${app.env.API_URL}document-provision-pack/v4`,
  /** 業務ルール_文書明細拡張項目規定取得API */ BUSINESS_RULE_DOCUMENT_STATEMENT: `${app.env.API_URL}document-statement-extension-item-provision/v1`,
  /** 業務ルール_自社管理項目規定API */ BUSINESS_RULE_COMPANY: `${app.env.API_URL}private-fields-provision/v1`,
  /** 仕掛中発注書画面_初期表示データ取得API */ IN_PROCESS_ORDER_DOCUMENT: `${app.env.API_URL}in-process-order-document-page/v3`,
  /** 修正中発注書画面_初期表示データ取得API */ IN_REVISION_ORDER_DOCUMENT: `${app.env.API_URL}in-revision-order-document-page/v3`,
  /** 下書き中発注書画面_初期表示データ取得API */ DRAFT_ORDER_PAGE: `${app.env.API_URL}draft-order-document-page/v3`,
  /** 発注書起票(下書き)API */ DRAFT_ORDER: `${app.env.API_URL}pre-order-document/v2`,
  /** 下書き発注書削除API */ DRAFT_ORDER_DELETE: `${app.env.API_URL}pre-order-document/delete/v1`,
  /** 発注書API */ ORDER: `${app.env.API_URL}order-document/v2`,
  /** 発注書PDF API */ ORDER_PDF: `${app.env.API_URL}order-document/v1`,
  /** 発注書画面_初期表示データ取得API */ ORDER_PAGE: `${app.env.API_URL}order-document-page/v4`,
  /** 発注書差し戻しAPI */ ORDER_SEND_BACK: `${app.env.API_URL}order-document/sendback/v2`,
  /** 発注辞退書提出API*/ ORDER_DECLINATURE_DOCUMENT: `${app.env.API_URL}order-declinature-document/v1`,
  /** 発注書複写API */ ORDER_COPY: `${app.env.API_URL}order-document/copy/v1`,
  /** 仕掛中発注請書画面_初期表示データ取得API */ IN_PROCESS_ORDER_CONFIRMATION_DOCUMENT: `${app.env.API_URL}in-process-order-confirmation-document-page/v2`,
  /** 発注請API */ ORDER_CONFIRMATION: `${app.env.API_URL}order-confirmation-document/v1`,
  /** 発注請書画面_初期表示データ取得API */ ORDER_CONFIRMATION_PAGE: `${app.env.API_URL}order-confirmation-document-page/v3`,
  /** 仕掛中納品書画面_初期表示データ取得API */ IN_PROCESS_DELIVERY_DOCUMENT: `${app.env.API_URL}in-process-delivery-document-page/v2`,
  /** 修正中納品書画面_初期表示データ取得API */ IN_REVISION_DELIVERY_DOCUMENT: `${app.env.API_URL}in-revision-delivery-document-page/v3`,
  // v1は納品書PDF印刷で使用。v2は納品書新規作成の提出と納品書修正提出で使用。
  /** 納品API */ DELIVERY_PDF: `${app.env.API_URL}delivery-document/v1`,
  /** 納品API */ DELIVERY: `${app.env.API_URL}delivery-document/v2`,
  /** 納品書画面_初期表示データ取得API */ DELIVERY_PAGE: `${app.env.API_URL}delivery-document-page/v3`,
  /** 納品承認API */ DELIVERY_APPROVE: `${app.env.API_URL}delivery-document/approve/v1`,
  /** 納品差し戻しAPI */ DELIVERY_SEND_BACK: `${app.env.API_URL}delivery-document/sendback/v1`,
  /** 仕掛中検収書画面_初期表示データ取得API */ IN_PROCESS_ACCEPTANCE_DOCUMENT: `${app.env.API_URL}in-process-acceptance-document-page/v2`,
  /** 修正中検収書画面_初期表示データ取得API */ IN_REVISION_ACCEPTANCE_DOCUMENT: `${app.env.API_URL}in-revision-acceptance-document-page/v3`,
  // v1はPDF出力で使用。v2は検収書新規作成の提出と修正提出で使用。
  /** 検収API */ ACCEPTANCE: `${app.env.API_URL}acceptance-document/v1`,
  /** 検収API */ ACCEPTANCE_CREATE: `${app.env.API_URL}acceptance-document/v2`,
  /** 検収書画面_初期表示データ取得API */ ACCEPTANCE_PAGE: `${app.env.API_URL}acceptance-document-page/v3`,
  /** 検収承認API */ ACCEPTANCE_APPROVE: `${app.env.API_URL}acceptance-document/approve/v1`,
  /** 検収差し戻しAPI */ ACCEPTANCE_SEND_BACK: `${app.env.API_URL}acceptance-document/sendback/v1`,
  /** 仕掛中納品転写検収書画面_初期表示データ取得API */ IN_PROCESS_DELIVERY_TRANSCRIBE_ACCEPTANCE: `${app.env.API_URL}estimate-each-time/in-process-acceptance-document-page/transcribe-delivery/v1`,
  /** 仕掛中明細訂正書画面_初期表示データ取得API */ IN_PROCESS_STATEMENT_MODIFY: `${app.env.API_URL}estimate-each-time/in-process-statement-modify-document-page/v1`,
  /** 修正中明細訂正書画面_初期表示データ取得API */ IN_REVISION_STATEMENT_MODIFY: `${app.env.API_URL}estimate-each-time/in-revision-statement-modify-document-page/v1`,
  /** 明細訂正書提出API */ STATEMENT_MODIFY: `${app.env.API_URL}estimate-each-time/statement-modify/v1`,
  /** 明細訂正書画面_初期表示データ取得API */ STATEMENT_MODIFY_PAGE: `${app.env.API_URL}estimate-each-time/statement-modify-document-page/v1`,
  /** 明細訂正承認API */ STATEMENT_MODIFY_APPROVE: `${app.env.API_URL}estimate-each-time/statement-modify/approve/v1`,
  /** 明細訂正差し戻しAPI */ STATEMENT_MODIFY_SEND_BACK: `${app.env.API_URL}estimate-each-time/statement-modify/sendback/v1`,
  /** 明細訂正否認API */ STATEMENT_MODIFY_REJECT: `${app.env.API_URL}estimate-each-time/statement-modify/reject/v1`,
  /** 仕掛中請求書画面_初期表示データ取得API */ IN_PROCESS_INVOICE_DOCUMENT: `${app.env.API_URL}in-process-invoice-page/v3`,
  /** 請求書提出予約API */ INVOICE_DOCUMENT_RESERVE: `${app.env.API_URL}invoice-document/reserve/v4`,
  /** 請求書画面_初期表示データ取得API */ INVOICE_PAGE: `${app.env.API_URL}invoice-document-page/v2`,
  /** 明細合計計算API */ STATEMENT_CALCULATE: `${app.env.API_URL}total-statement-amount/calculate/v1`,
  /** 訂正明細計算API */ STATEMENT_CALCULATE_MODIFY: `${app.env.API_URL}total-statement-amount/calculate/statement-modify/v1`,
  /** 明細追加訂正計算API */ ADDITIONAL_STATEMENT_CALCULATE: `${app.env.API_URL}total-statement-amount/calculate/additional/v1`,
  /** 明細訂正書PDF出力API */ STATEMENT_MODIFY_DOCUMENT: `${app.env.API_URL}estimate-each-time/statement-modify-document/v1`,

  // 出来高で使用
  /** 業務ルール_出来高テンプレート新規作成 */ VOLUME_BUSINESS_RULE_CREATE: `${app.env.API_URL}business-rule/volume/v4`,
  /** 業務ルール_出来高業務規定取得API */ VOLUME_BUSINESS_RULE_PROVISION: `${app.env.API_URL}volume/business-provision/v1`,
  /** 業務ルール_出来高文書規定パック取得API（編集でも使用（出来高文書規定パック変更API）） */ VOLUME_BUSINESS_RULE_DOCUMENT: `${app.env.API_URL}volume/document-provision-pack/v4`,
  // VOLUME_BUSINESS_RULE_DOCUMENT_STATEMENTとVOLUME_BUSINESS_RULE_DOCUMENT_STATEMENT_EDITはバージョンの違いのみでパスは同一
  /** 業務ルール_出来高文書明細拡張項目規定取得API（取得） */ VOLUME_BUSINESS_RULE_DOCUMENT_STATEMENT: `${app.env.API_URL}volume/document-statement-extension-item-provision/v2`,
  /** 業務ルール_出来高文書明細拡張項目規定取得API(編集) */ VOLUME_BUSINESS_RULE_DOCUMENT_STATEMENT_EDIT: `${app.env.API_URL}volume/document-statement-extension-item-provision/v1`,
  /** 業務ルール_出来高自社管理項目規定取得API */ VOLUME_BUSINESS_RULE_COMPANY: `${app.env.API_URL}volume/private-fields-provision/v1`,
  /** 修正中出来高発注書画面_初期表示データ取得API */ VOLUME_IN_REVISION_ORDER_DOCUMENT: `${app.env.API_URL}volume/in-revision-order-document-page/v4`,
  /** 下書き中出来高発注書画面_初期表示データ取得API */ VOLUME_DRAFT_ORDER_PAGE: `${app.env.API_URL}volume/draft-order-page/v4`,
  /** 出来高発注起票(下書き)API */ VOLUME_DRAFT_ORDER: `${app.env.API_URL}volume/order/draft/v3`,
  /** 下書き出来高発注削除API */ VOLUME_DRAFT_ORDER_DELETE: `${app.env.API_URL}volume/order/delete/v1`,
  /** 出来高発注書提出API */ VOLUME_ORDER: `${app.env.API_URL}volume/order/v3`,
  /** 出来高発注書画面_初期表示データ取得API */ VOLUME_ORDER_PAGE: `${app.env.API_URL}order-document-page/volume/v4`,
  /** 出来高発注差し戻しAPI */ VOLUME_ORDER_SEND_BACK: `${app.env.API_URL}volume/order/sendback/v1`,
  /** 出来高発注辞退API*/ VOLUME_ORDER_DECLINATURE: `${app.env.API_URL}volume/order/decline/v1`,
  /** 出来高発注書複写API */ VOLUME_ORDER_COPY: `${app.env.API_URL}volume/order/copy/v1`,
  /** 仕掛中出来高発注請書画面_初期表示データ取得API */ VOLUME_IN_PROCESS_CONFIRMATION_DOCUMENT: `${app.env.API_URL}in-process-order-confirmation-document-page/volume/v3`,
  /** 出来高発注請API */ VOLUME_ORDER_CONFIRMATION: `${app.env.API_URL}volume/order-confirm/v1`,
  /** 出来高発注請書画面_初期表示データ取得API */ VOLUME_ORDER_CONFIRMATION_PAGE: `${app.env.API_URL}order-confirmation-document-page/volume/v2`,
  /** 仕掛中出来高報告書画面_初期表示データ取得API*/ VOLUME_IN_PROCESS_VOLUME_REPORT: `${app.env.API_URL}in-process-volume-report-page/v3`,
  /** 修正中出来高報告書画面_初期表示データ取得API */ VOLUME_IN_REVISION_VOLUME_REPORT_PAGE: `${app.env.API_URL}in-revision-volume-report-page/v3`,
  /** 出来高報告API*/ VOLUME_REPORT: `${app.env.API_URL}volume-report/v2`,
  /** 出来高報告書画面_初期表示データ取得API*/ VOLUME_REPORT_PAGE: `${app.env.API_URL}volume-report-page/v4`,
  /** 出来高報告承認API */ VOLUME_REPORT_APPROVE: `${app.env.API_URL}volume-report/approve/v1`,
  /** 出来高報告差し戻しAPI */ VOLUME_REPORT_SEND_BACK: `${app.env.API_URL}volume-report/sendback/v1`,
  /** 仕掛中出来高追加発注書画面_初期表示データ取得API */ VOLUME_IN_PROCESS_PURCHASE_ADD_DOCUMENT: `${app.env.API_URL}in-process-additional-order-page/volume/v3`,
  /** 修正中出来高追加発注書画面_初期表示データ取得API */ VOLUME_IN_REVISION_PURCHASE_ADD_DOCUMENT: `${app.env.API_URL}volume/in-revision-additional-order-page/v4`,
  /** 出来高追加発注API */ VOLUME_PURCHASE_ADD: `${app.env.API_URL}volume/additional-order/v3`,
  /** 出来高追加発注書画面_初期表示データ取得API */ VOLUME_PURCHASE_ADD_PAGE: `${app.env.API_URL}additional-order-document-page/volume/v3`,
  /** 出来高追加発注差し戻しAPI */ VOLUME_PURCHASE_ADD_SEND_BACK: `${app.env.API_URL}volume/additional-order/sendback/v1`,
  /** 出来高追加発注否認API */ VOLUME_PURCHASE_ADD_REJECT: `${app.env.API_URL}volume/additional-order/reject/v1`,
  /** 仕掛中出来高追加発注請書画面_初期表示データ取得API */ VOLUME_IN_PROCESS_PURCHASE_ADD_CONFIRMATION: `${app.env.API_URL}in-process-additional-order-confirm-page/volume/v4`,
  /** 出来高追加発注請API */ VOLUME_PURCHASE_ADD_CONFIRMATION: `${app.env.API_URL}additional-order-confirm/volume/v2`,
  /** 出来高追加発注請書画面_初期表示データ取得API */ VOLUME_PURCHASE_ADD_CONFIRMATION_PAGE: `${app.env.API_URL}additional-order-confirmation-document-page/volume/v2`,
  /** 仕掛中出来高請求書画面_初期表示データ取得API */ VOLUME_IN_PROCESS_INVOICE: `${app.env.API_URL}volume/in-process-invoice-page/v1`,
  /** 出来高請求書提出予約API */ VOLUME_INVOICE_RESERVE: `${app.env.API_URL}volume/invoice/reserve/v1`,
  /** 出来高請求書画面_初期表示データ取得API */ VOLUME_INVOICE_PAGE: `${app.env.API_URL}volume/invoice-document-page/v1`,
  /** 仕掛中出来高明細訂正書画面_初期表示データ取得API */ VOLUME_IN_PROCESS_STATEMENT_MODIFY: `${app.env.API_URL}volume/in-process-statement-modify-document-page/v1`,
  /** 修正中出来高明細訂正書画面_初期表示データ取得API */ VOLUME_IN_REVISION_STATEMENT_MODIFY: `${app.env.API_URL}volume/in-revision-statement-modify-document-page/v1`,
  /** 出来高明細訂正書提出API */ VOLUME_STATEMENT_MODIFY: `${app.env.API_URL}volume/statement-modify/v1`,
  /** 出来高明細訂正書画面_初期表示データ取得API */ VOLUME_STATEMENT_MODIFY_PAGE: `${app.env.API_URL}volume/statement-modify-document-page/v1`,
  /** 出来高明細訂正承認API */ VOLUME_STATEMENT_MODIFY_APPROVE: `${app.env.API_URL}volume/statement-modify/approve/v1`,
  /** 出来高明細訂正差し戻しAPI */ VOLUME_STATEMENT_MODIFY_SEND_BACK: `${app.env.API_URL}volume/statement-modify/sendback/v1`,
  /** 出来高明細訂正否認API */ VOLUME_STATEMENT_MODIFY_REJECT: `${app.env.API_URL}volume/statement-modify/reject/v1`,
  /** 工事案件選択API*/ VOLUME_CONSTRUCTION: `${app.env.API_URL}construction-page/v4`,
  /** 出来高金額計算API*/ VOLUME_REPORT_STATEMENT_CALCULATE: `${app.env.API_URL}total-statement-amount/volume/calculate/v3`,
  /** 出来高訂正明細計算API */ VOLUME_STATEMENT_CALCULATE_MODIFY: `${app.env.API_URL}total-statement-amount/calculate/volume/statement-modify/v1`,
  /** 出来高発注書PDF出力API */ VOLUME_ORDER_DOCUMENT: `${app.env.API_URL}volume/order-document/v1`,
  /** 出来高発注請書PDF出力API */ VOLUME_ORDER_CONFIRMATION_DOCUMENT: `${app.env.API_URL}volume/order-confirmation-document/v1`,
  /** 出来高報告書PDF出力API */ VOLUME_REPORT_DOCUMENT: `${app.env.API_URL}volume-report-document/v1`,
  /** 出来高追加発注書PDF出力API */ VOLUME_PURCHASE_ADD_DOCUMENT: `${app.env.API_URL}volume/additional-order-document/v1`,
  /** 出来高追加発注請書PDF出力API */ VOLUME_PURCHASE_ADD_CONFIRMATION_DOCUMENT: `${app.env.API_URL}volume/additional-order-confirmation-document/v1`,
  /** 出来高明細訂正書PDF出力API */ VOLUME_STATEMENT_MODIFY_DOCUMENT: `${app.env.API_URL}volume/statement-modify-document/v1`,

  /**
   * ####################################################################################################
   * ワークフロー連携
   * ####################################################################################################
   */
  /** 社内申請 - 発注書（通常） | method: POST */
  WORKFLOW_ORDER: `${app.env.API_URL}order-document/internal-apply/v2`,
  /** 社内申請 - 下書き発注書（通常） | method: PUT, query: [individualTradeId] */
  WORKFLOW_DRAFT_ORDER: `${app.env.API_URL}order-document/internal-apply/v2`,
  /** 社内申請 - 修正済発注書（通常） | method: POST, query: [individualTradeId] */
  WORKFLOW_MODIFIED_ORDER: `${app.env.API_URL}order-document/internal-apply/v2`,
  /** 社内申請 - 明細数量訂正（通常） | method: POST, query: [individualTradeId] */
  WORKFLOW_STATEMENT_MODIFY: `${app.env.API_URL}statement-quantity-modify-document/internal-apply/v1`,

  /** 社内申請 - 発注書（出来高） | method: POST */
  WORKFLOW_VOLUME_ORDER: `${app.env.API_URL}volume/order/internal-apply/v2`,
  /** 社内申請 - 下書き発注書（出来高） | method: PUT, query: [individualTradeId] */
  WORKFLOW_VOLUME_DRAFT_ORDER: `${app.env.API_URL}volume/order/internal-apply/v2`,
  /** 社内申請 - 修正済発注書（出来高） | method: POST, query: [individualTradeId] */
  WORKFLOW_VOLUME_MODIFIED_ORDER: `${app.env.API_URL}volume/order/internal-apply/v2`,
  /** 社内申請 - 追加発注（出来高） | method: POST, query: [individualTradeId] */
  WORKFLOW_VOLUME_PURCHASE_ADD: `${app.env.API_URL}volume/additional-order/internal-apply/v2`,
  /** 社内申請 - 修正済追加発注書（出来高） | method: POST, query: [individualTradeId] */
  WORKFLOW_VOLUME_MODIFIED_PURCHASE_ADD: `${app.env.API_URL}volume/additional-order/internal-apply/v2`,

  /** ワークフロー承認後の手動送信API */
  WORKFLOW_MANUAL_SEND: `${app.env.API_URL}document-workflow/manual-send/v1`,

  /** 社内申請中 発注書修正 - 初期表示データ取得 兼 修正実行 | method: GET or PUT, query: [individualTradeId]/[documentId] */
  INTERNAL_APPLYING_ORDER_MODIFY: `${app.env.API_URL}internal-applying-order-document-modify-page/v2`,
  /** 社内申請中 出来高発注書修正 - 初期表示データ取得 兼 修正実行 | method: GET or PUT, query: [individualTradeId]/[documentId] */
  INTERNAL_APPLYING_VOLUME_ORDER_MODIFY: `${app.env.API_URL}volume/internal-applying-order-document-modify-page/v2`,
  /** 社内申請中 出来高追加発注書修正 - 初期表示データ取得 兼 修正実行 | method: GET or PUT, query: [individualTradeId]/[documentId] */
  INTERNAL_APPLYING_VOLUME_PURCHASE_ADD_MODIFY: `${app.env.API_URL}volume/internal-applying-additional-order-document-modify-page/v2`,
};
